//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Intranet.Models
{
    public partial class Employee
    {
        public Employee()
        {
            this.Requests = new HashSet<Request>();
            this.Requests1 = new HashSet<Request>();
        }
    
        public int EmployeeId { get; set; }
        public Nullable<int> id_men { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string EmployeeNumber { get; set; }
        public string Department { get; set; }
        public string Office { get; set; }
        public Nullable<System.DateTime> IncomeDate { get; set; }
        public Nullable<System.DateTime> DismissDate { get; set; }
        public byte DSC { get; set; }
        public string Login { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
        public virtual RequestApprover RequestApprover { get; set; }
        public virtual ICollection<Request> Requests1 { get; set; }
    }
    
}
