//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Intranet.Models
{
    public partial class RequestFreight
    {
        public RequestFreight()
        {
            this.RequestFreightCargoes = new HashSet<RequestFreightCargo>();
        }
    
        public int RequestId { get; set; }
        public string OrderNumber { get; set; }
        public string LoadingType { get; set; }
        public string LoadingAddress { get; set; }
        public string ContactName { get; set; }
        public string Responsible { get; set; }
        public string VehicleType { get; set; }
        public string DestinationPoint { get; set; }
        public string LoadingTime { get; set; }
        public string Shipper { get; set; }
        public string Consignee { get; set; }
        public string ConsigneeContactName { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<int> VehicleCount { get; set; }
        public Nullable<int> VehicleCapacityTonns { get; set; }
        public bool MobileConnection { get; set; }
        public bool LocationInfo { get; set; }
        public bool ChangesInfo { get; set; }
        public bool WithInvoice { get; set; }
    
        public virtual ICollection<RequestFreightCargo> RequestFreightCargoes { get; set; }
        public virtual Request Request { get; set; }
    }
    
}
