//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Intranet.Models
{
    public partial class RequestCrane
    {
        public RequestCrane()
        {
            this.RequestCraneSlingers = new HashSet<RequestCraneSlinger>();
        }
    
        public int RequestId { get; set; }
        public string LicenceNumber { get; set; }
        public string WorkPlace { get; set; }
        public string WorkObject { get; set; }
        public string WorkType { get; set; }
        public string CraneType { get; set; }
        public bool PowerLineExists { get; set; }
        public string PowerPermission { get; set; }
        public string Responsible { get; set; }
        public bool ProjectExists { get; set; }
        public string ResponsibleOrder { get; set; }
        public string CustomerName { get; set; }
    
        public virtual ICollection<RequestCraneSlinger> RequestCraneSlingers { get; set; }
        public virtual Request Request { get; set; }
    }
    
}
