//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Intranet.Models
{
    public partial class RequestFreightCargo
    {
        public int CargoId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string CargoName { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string DestAdress { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual RequestFreight RequestFreight { get; set; }
        public virtual Request Request { get; set; }
    }
    
}
