//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Intranet.Models
{
    public partial class RequestCraneSlinger
    {
        public int SlingerId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string Office { get; set; }
        public string FIO { get; set; }
        public string CertificateNumber { get; set; }
        public Nullable<System.DateTime> DateKnowledge { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual RequestCrane RequestCrane { get; set; }
        public virtual Request Request { get; set; }
    }
    
}
