//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Intranet.Models
{
    public partial class RequestPassenger
    {
        public int RequestId { get; set; }
        public string DestinationPoint { get; set; }
        public Nullable<short> PassengerAmount { get; set; }
        public Nullable<short> ChildAmount { get; set; }
        public string TripPurpose { get; set; }
        public string SeatPlace { get; set; }
        public Nullable<short> TripDuration { get; set; }
        public string SecondedPeople { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderName { get; set; }
    
        public virtual Request Request { get; set; }
    }
    
}
