//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Intranet.Models
{
    public partial class Request
    {
        public Request()
        {
            this.RequestAttachments = new HashSet<RequestAttachment>();
            this.RequestEvents = new HashSet<RequestEvent>();
            this.RequestCraneSlingers = new HashSet<RequestCraneSlinger>();
            this.RequestFreightCargoes = new HashSet<RequestFreightCargo>();
        }
    
        public int RequestId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserFio { get; set; }
        public string UserLogin { get; set; }
        public Nullable<int> ApproverEmployeeId { get; set; }
        public string ApproverFio { get; set; }
        public string ApproverLogin { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RequestTaskId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<RequestAttachment> RequestAttachments { get; set; }
        public virtual RequestFreight RequestFreight { get; set; }
        public virtual ICollection<RequestEvent> RequestEvents { get; set; }
        public virtual RequestCrane RequestCrane { get; set; }
        public virtual ICollection<RequestCraneSlinger> RequestCraneSlingers { get; set; }
        public virtual RequestPassenger RequestPassenger { get; set; }
        public virtual ICollection<RequestFreightCargo> RequestFreightCargoes { get; set; }
        public virtual v_RequestCustomers v_RequestCustomer { get; set; }
    }
    
}
