//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Intranet.Models
{
    public partial class RequestEvent
    {
        public int RequestEventId { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string Message { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RequestId { get; set; }
    
        public virtual Request Request { get; set; }
    }
    
}
