//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Intranet.Models
{
    public partial class ServiceDepartment
    {
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public int ServiceDepartmentGroupId { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> ParentDepartmentId { get; set; }
    }
    
}
