//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Intranet.Models
{
    public partial class transportEntities : DbContext
    {
        public transportEntities()
            : base("name=transportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RequestPassenger> RequestPassengers { get; set; }
        public DbSet<RequestCraneSlinger> RequestCraneSlingers { get; set; }
        public DbSet<RequestCrane> RequestCranes { get; set; }
        public DbSet<RequestFreightCargo> RequestFreightCargoes { get; set; }
        public DbSet<RequestFreight> RequestFreights { get; set; }
        public DbSet<RequestAttachment> RequestAttachments { get; set; }
        public DbSet<RequestEvent> RequestEvents { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Request> Requests { get; set; }
        public DbSet<RequestApprover> RequestApprovers { get; set; }
        public DbSet<v_RequestCustomers> v_RequestCustomers { get; set; }
        public DbSet<v_RequestType> v_RequestType { get; set; }
        public DbSet<RequestInternational> RequestInternationals { get; set; }
        public DbSet<view_ServiceDepartmentGroup> view_ServiceDepartmentGroup { get; set; }
        public DbSet<view_ServiceDirection> view_ServiceDirection { get; set; }
        public DbSet<view_ServicePurpose> view_ServicePurpose { get; set; }
        public DbSet<ServiceDepartment> ServiceDepartments { get; set; }
    }
}
