//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Intranet.Models
{
    public partial class v_RequestCustomers
    {
        public v_RequestCustomers()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string SHZ { get; set; }
        public Nullable<int> DirectionId { get; set; }
        public Nullable<int> PurposeId { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
    
}
